service: serverless-color-tracking

frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  profile: default
  region: us-east-1
  logRetentionInDays: 7
  environment:
    DYNAMODB_STATS_TABLE: ${self:service}-${sls:stage}-statsTable
    KINESIS_CLICKS_STREAM: ${self:service}-${sls:stage}-clicksStream
    KINESIS_HOVERS_STREAM: ${self:service}-${sls:stage}-hoversStream
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - kinesis:GetRecords
            - kinesis:GetShardIterator
            - kinesis:DescribeStream
            - kinesis:ListStreams
            - kinesis:PutRecord
            - kinesis:PutRecords
          Resource:
            - Fn::GetAtt: [kinesisClicksStream, Arn]
        - Effect: Allow
          Action:
            - kinesis:GetRecords
            - kinesis:GetShardIterator
            - kinesis:DescribeStream
            - kinesis:ListStreams
            - kinesis:PutRecord
            - kinesis:PutRecords
          Resource:
            - Fn::GetAtt: [kinesisHoversStream, Arn]
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_STATS_TABLE}"

functions:
  createEvent:
    handler: lambdas/endpoints/v1/events/producer.handler
    events:
      - http:
          path: /v1/events
          method: post
          cors: true

  clicksConsumer:
    handler: lambdas/kinesis/consumers/clicks.handler
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - kinesisClicksStream
              - Arn

  hoversConsumer:
    handler: lambdas/kinesis/consumers/hovers.handler
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - kinesisHoversStream
              - Arn

  getStats:
    handler: lambdas/endpoints/v1/stats/get.handler
    events:
      - http:
          path: /v1/stats
          method: get
          cors: true

resources:
  Resources:
    kinesisClicksStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:provider.environment.KINESIS_CLICKS_STREAM}
        RetentionPeriodHours: 24
        ShardCount: 1
    kinesisHoversStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:provider.environment.KINESIS_HOVERS_STREAM}
        RetentionPeriodHours: 24
        ShardCount: 1
    StatsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_STATS_TABLE}
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
